name: C/C++ CI

on:
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - run: wget https://www.libsdl.org/release/SDL2-2.0.10.tar.gz -O SDL2-2.0.10.tar.gz
    - run: tar -xzvf SDL2-2.0.10.tar.gz
    - run: (cd SDL2-2.0.10 && ./configure && make && sudo make install)
    - name: make all
      run: make all
      
